apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - "./infra/k8s/*.yaml"
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: neural-hour-337318
  artifacts:
    - image: us.gcr.io/neural-hour-337318/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/neural-hour-337318/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
