apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - './infra/k8s/*.yaml'
build:
  local:
    push: false
  artifacts:
    - image: refbit/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .