name: deploy-auth

on:
  push:
    branches: 
      - main
    paths: 
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t refbit/auth .
      - run: 
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          $DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          $DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - run: docker push refbit/auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save micro-ticketing
      - run: kubectl rollout restart deployment auth
